# Generated by Django 3.2.13 on 2022-05-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
